### ISSUE TITLE
Are install instructions correct?

### ISSUE THREAD

**Issue by takuhii** [TheOfficialFloW/GePatch#6]
Hi
In your installation instructions it says to;
Copy it to ux0:pspemu/seplugins/

Then write this line 
ms0:/seplugins/ge_patch.prx 1

to
ux0:pspemu/seplugins/game.txt

But I just copied that file to **ux0**? 

Do I copy it to both locations?

**Comment by crazy2k4** [comment]
yes,work in both locations(ur0-ux0)

**Comment by AceCuba** [comment]
Good luck finding ms0:/ with Vitashell

**Comment by Masamune3210** [comment]
ms0: is mounted wherever you have it set to in Adrenaline settings, the default is ux0:pspemu.
You put the plugin in ux0:pspemu/seplugins with default settings, and modify the game.txt file with the line 
ms0:/seplugins/ge_patch.prx 1
because that is how it appears to the emulated psp inside of adrenaline
